name: diffComp
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - matplotlib
  - pybedtools
  - pandas
  - htslib
  - python>=3.8
  - pip

  - pip:
     - -e .  # install git checkout of demo-dsproject in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - ipython
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
